### PR TITLE
Repository Refactoring

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Consider updating the description**
  *( Check the preview repos description )*

  <br>

- ***[Disable Unused Tabs][Tabs]***:

  - `Actions`

<br>
<br>

## ![Badge Changes]

- Sorted files

- General formattin / spacing

- Moved usage / dev sections into dedicated files

- Added quicklinks

- Added license badge

- Added more links to referenced resources

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/RSSingle

### CODE REVIEW

**Comment by ElectronicsArchiver** [comment]
Closed without comment, thank you, very helpful.

**Comment by tanrax** [comment]
Sorry @ElectronicsArchiver , my sincere apologies. I thought you were a robot that automatically adds pull request. I have had problems in the past. 
Let's get back to your pull request. I've been reviewing the changes you propose and I don't see any justification for modifying the README for aesthetic reasons. If it were to improve its comprehension, it would be interesting to incorporate. I also don't understand why you want to move the code to separate folders.
Best regards.

**Comment by ElectronicsArchiver** [comment]
<br>

I see, no worries~
 
*I heard the same thing about bots before,* 
*however I haven't seen it myself yet~*

<br>

## Arguments

1. Aesthetics are part of making things 
   more comprehensible / readable.

<br>

2. Moving the documentation as well as the 
   code into separate files / folders has 
   many good reasons:
  
    - Smaller pieces of content are more easily comprehensible, 
      for example, a README acts as a frontpage to a project and 
      should generally speaking give the user an overview of the 
      options they have.
  
      As such keeping it small and full of links / buttons 
      to resources they may wanna see it practical.
    
    - Keeping files from the root folder helps not only the 
      README to be more accessible - not further down than it
      needs to be - but also to make the project structure 
      clear as well.
    
      To begin with, it's a shame how nowadays the root of 
      repositories is usually cluttered with config files, 
      which often dont even allow to be placed into a 
      dedicated folder.
    
    - Users don't see what they didn't ask for - If you come to 
      a project and get bashed in the face with information for 
      everything, often times users may choose to look on to a 
      project that doesn't.
    
      Recurring users on the other hand may search for a specific 
      topic, but have to look through things they don't care about 
      to find what they wanted.
    
      Separating docs / code into small named 
      / linked pieces can help in this regard.
    
    - Clean structure makes projects more maintainable.
    
      If someone wants to contribute / maintain a project, they 
      usually have to be able to comprehend it as a whole as to 
      not make misjudged changes.
    
      The same argument as in the precious sections applies here.

<br>
<br>

## Note

~~*( Wrote this on mobile, may have to adjust the <br>
formatting, hope it's not too jumbled up )*~~

<br>

**Comment by tanrax** [comment]
Hi again, I love your energy, dedication and effort. Your arguments are valid, but subjective. At the moment I don't want to visually improve neither the code structure nor the appearance of the README. It is clear enough. I want it to be as simple as possible. If someone is unable to understand how to contribute code, they are probably not ready for it. In any case I would already create a CONTRIBUTE.md explaining the steps.
I thank you for your contribution, but this is not the time. Feel free to make a fork anyway.
Best regards and thank you very much.

**Pull request closed without merging**
