### PR TITLE
Fix format error

### PR DESCRIPTION
**Pull request by tanrax**

### CODE REVIEW

**Comment by tanrax** [comment]
@shymega Fix the bug https://github.com/tanrax/RSSingle/issues/17

**Comment by shymega** [comment]
Good catch. I guess I only thought of `KeyError` as an `Exception` subclass there. The only thing I'd add is that this PR appears to change multiple things, making it hard to track down future bugs. Maybe splitting the changes into a PR _each_ would be better? Up to you - otherwise, good catch on my previous oversight! :+1:

**Comment by shymega** [comment]
OK, after some rebasing, I've adjusted the PR. I've also done this to #16, to make it one change per PR.

What formatting tool did you use? What would be a good plan, is to branch from `master`, run the linter, and then make a PR. Otherwise, branching from feature or bug-fix PRs includes commits that aren't necessarily related to the PR.

(Heads-up: this has been force-pushed, so you'll need to do a `git pull --rebase`)

**Comment by shymega** [comment]
The only thing left to change in this PR is to split the 'format string' change, and the Exception catch change. I will leave that to you because I'm conscious I might have overstepped my bounds.

**Pull request merged**
