### PR TITLE
Initial version of CI for RSSingle

### PR DESCRIPTION
**Pull request by shymega**
Hi @tanrax!

As part of our new collaboration, I've made an initial version for automated CI for RSSingle.

It needs macOS to work first, so I've commented out a draft version of the `pyinstaller` aspect, so I'll make this PR a draft for now when we can discuss further, preferably in a GH issue for transparency (unless you want it private?), but this workflow tests on PRs and pushes to any branch, with flake8 across multiple Python versions. The pyinstaller aspect only runs if the flake8 check passes.

What do you think?

Signed-off-by: Dom Rodriguez <shymega@shymega.org.uk>

### CODE REVIEW

**Comment by shymega** [comment]
I'm also working on automated container image builds (for those who want to use a container), and Python linting/type checks. All this I don't expect you to merge, as it's your project, but I just wanted to help make it better.

**Comment by shymega** [comment]
Rebased and squashed the last two commits.

**Comment by tanrax** [comment]
What problems does MacOS have with pyinstaller?

**Comment by shymega** [comment]
I don't really remember, I worked on this a long time ago now in relative terms.

I think the issue was due to the way macOS launches `pyinstaller`-packaged applications. There was an issue with the fix I incorporated into the CI workflow. I'll probably adjust it to upload based on the 'runner', so Windows/macOS/Linux.

**Comment by shymega** [comment]
I've just adjusted the PR, I now need to work out how to create releases. Might be a bit noisy. I'll be testing on my fork, in a separate branch.

**Pull request merged**
